Add filters to the history table
PayMeService/remotisan pull request #31
Opened 2024-08-07 14:10 UTC by matanavgi

Add filters to the history table: user selection and free search for the commands/parameters

2024-08-07 14:44 UTC, ranbahar submitted a review, later dismissed

2024-08-07 14:49 UTC, o-kima commented on resources/views/scripts.blade.php
> +    var filters = "?page=" + page + "&user=" + $scope.user + "&command=" + $scope.searchable;
`new URLSearchParams({page: page, user: $scope.user, command: $scope.searchable}).toString()`

2024-08-07 14:57 UTC, o-kima commented on src/Http/Controllers/RemotisanController.php
> +        } elseif ($request->input("user") != "All") {
send user=null and not `all` in case of choosing all

2024-08-07 15:21 UTC, matanavgi commented on resources/views/scripts.blade.php
> +    var filters = "?page=" + page + "&user=" + $scope.user + "&command=" + $scope.searchable;
Nice

2024-08-08 07:54 UTC, o-kima requested changes

2024-08-08 08:56 UTC, matanavgi commented on src/Http/Controllers/RemotisanController.php
> +        } elseif ($request->input("user") != "All") {
NULL transform to "null" from JS.
Statement will be `$request->input("user") != "null"`

2024-08-08 09:09 UTC, matanavgi commented on src/Models/Execution.php
> +    public static function getUsers(): array
User (user_identifier) is an attribute of the Execution model. Shouldn't it be there?
Maybe change the function name to `getUsersByIdentifier()`?

2024-08-08 12:55 UTC, o-kima approved these changes

2024-08-11 05:33 UTC, merged