Audit history kill and view old logs
PayMeService/remotisan pull request #4
Opened 2023-01-09 15:13 UTC by xbugster

2023-01-09 16:08 UTC, kima92 reviewed
the most serious one is how to make sure the kill is being executed on the same server

2023-01-09 16:08 UTC, kima92 commented on src/Remotisan.php
> +    public function audit(int $pid, string $uuid, int $timestamp, string $command, string $params, string $userDisplayName): void
move to external class? also getHistoryScopedToUser

2023-01-09 16:08 UTC, kima92 commented on routes/web.php
> +    Route::post('/kill/{pid}', [RemotisanController::class, "killProcess"]);
how you make sure we got into the same server that executed the request?

2023-01-09 16:08 UTC, kima92 commented on src/Http/Controllers/RemotisanController.php
> +            $pid = $this->rt->killProcess($request->pid);
kill by uuid and not pid

2023-01-09 16:08 UTC, kima92 commented on src/Http/Controllers/RemotisanController.php
> +    public function killProcess(Request $request): array
add here the uuid/pid

2023-01-09 16:11 UTC, o-kima requested changes
comments from my other github.
the most serious one is how to make sure the kill is being executed on the same server

2023-01-09 17:17 UTC, kima92 commented on database/migrations/2022_12_27_145113_create_remotisan_audit_table.php
> +            $table->string("user_name")->index();
Add status: running, completed, failed, killed

2023-01-10 00:40 UTC, o-kima commented on src/Remotisan.php
> +    public static function authWith($role, callable $callable): void
rollback. the usage of Remotisan::authWith() is performed on the Facade and not on this class.

2023-01-10 00:40 UTC, o-kima commented on src/Remotisan.php
> +    public function getUserDisplayName():string
handle null callable
add space `: string`. remove `display`. just `getUserName`.
relevant also to function below and the static variable

2023-01-10 00:40 UTC, o-kima commented on src/ProcessExecutor.php
> +        return $pid;
return the process object itself, then pass it to audit function instead of pass the id and the command.
maybe even create a remotisan\process class to hold the symfony\process+uuid

2023-01-10 00:40 UTC, o-kima commented on src/Http/Controllers/RemotisanController.php
> +use Illuminate\Database\Eloquent\Collection;
remove?

2023-01-10 00:40 UTC, o-kima commented on src/Remotisan.php
> +            ->where("user_name", $this->getUserDisplayName())
show all commands from same user group?

2023-01-10 00:47 UTC, o-kima commented
can we write tests for this PR?

2023-01-24 14:06 UTC, xbugster commented on database/migrations/2022_12_27_145113_create_remotisan_audit_table.php
> +            $table->integer("executed_at")->unsigned()->index();
i want to write explicitly in this case.

2023-01-24 14:07 UTC, xbugster commented on src/Models/RemotisanAudit.php
> +class RemotisanAudit extends Model
it is exactly audit. we audit every execution with related data, who executed, which PID it had, when executed. etc.
we now need to invent how we notify ourself on execution finished and how it finished.

2023-01-24 14:13 UTC, o-kima commented on database/migrations/2022_12_27_145113_create_remotisan_audit_table.php
> +            $table->integer("executed_at")->unsigned()->index();
Eloquent timestamps are very explicit. its a framework standard.

if you want a different name, which I not recommend, you can override the Model::CREATED_AT const or `getCreatedAtColumn` function

2023-01-24 14:17 UTC, o-kima commented on src/Models/RemotisanAudit.php
> +class RemotisanAudit extends Model
if so, every db record in every system is audit :)
sales table is just an audit for sales. this table is for remotisan executions (audits)

2023-01-24 14:18 UTC, xbugster commented on src/Remotisan.php
> +    public function audit(int $pid, string $uuid, int $timestamp, string $command, string $params, string $userDisplayName): void
moved directly into controller.

2023-01-24 14:18 UTC, xbugster commented on routes/web.php
> +    Route::post('/kill/{pid}', [RemotisanController::class, "killProcess"]);
after long discussions with Ilya, it is said - we will only execute commands on "jobs".

2023-01-24 14:20 UTC, xbugster commented on src/Http/Controllers/RemotisanController.php
> +            $pid = $this->rt->killProcess($request->pid);
it would then require unnecessary call to sql to get the record by uuid and get its pid to proceed with kill, since you kill the job by PID on the server.

2023-01-24 14:31 UTC, o-kima commented on routes/web.php
> +    Route::post('/kill/{pid}', [RemotisanController::class, "killProcess"]);
what would be when jobs would have 2 instances? maybe we can think of different approaches?
for example, when saving a record, we save also the server executed it.
when requesting a kill request, we add the execution uuid to a redis array under the same name as the server written on the execution.
meanwhile, every server will have a demon process that check every second if there is records on his redis list, and if so it kills the process?

2023-01-24 14:42 UTC, xbugster commented on src/ProcessExecutor.php
> +        return $pid;
why complicate simple things ?
pid is enough, we got all the rest of data outside.
processExecutor is responsible for dealing with processes, why exposing process itself outside and letting it linger around the system ? :/

2023-01-24 14:43 UTC, xbugster commented on src/Http/Controllers/RemotisanController.php
> +use Illuminate\Database\Eloquent\Collection;
it is in use, since history() returns Collection

2023-01-24 14:43 UTC, xbugster commented on src/Remotisan.php
> +            ->where("user_name", $this->getUserDisplayName())
nope. Ilya said only user's ran commands.

2023-01-24 15:01 UTC, o-kima commented on src/ProcessExecutor.php
> +        return $pid;
i'm not sure its complicating things. its really easy and can give you benefits as i already write.

> processExecutor is responsible for dealing with processes, why exposing process itself outside
it would still be responsible, but not it would return a known object

> letting it linger around the system ? :/
you let the PID linger around the system anyway, currently without context of what it is. and if you can implement it without public `->getPID()` function it surely be more secure

2023-01-24 15:09 UTC, o-kima commented on src/Remotisan.php
> +        Audit::updateProcessStatusByUuid($uuid, ProcessStatuses::KILLED);
why query it again instead of update the `$auditRecord` instance?

2023-01-24 15:11 UTC, o-kima commented on src/Remotisan.php
> +            throw new UnauthenticatedException();
should we check kill access?

2023-01-24 16:07 UTC, xbugster commented on src/Http/Controllers/RemotisanController.php
> +            $pid = $this->rt->killProcess($request->pid);
true, forgot to check the same user identifier was on the record when killing process requested.
definitely something we want, as stated in second comment.

2023-01-24 16:11 UTC, xbugster commented on src/ProcessExecutor.php
> +        return $pid;
getPID is public method on symfony process which is not exposed by process executor.
allowing to linger id is way different than lingering instance. let's keep it single responsibility.

2023-01-24 16:13 UTC, xbugster commented on src/Remotisan.php
> +        Audit::updateProcessStatusByUuid($uuid, ProcessStatuses::KILLED);
to avoid modifying properties of model outside model and let the model handle it.

2023-01-24 16:30 UTC, o-kima commented on src/ProcessExecutor.php
> +        return $pid;
> getPID is public method on symfony process which is not exposed by process executor.
allowing to linger id is way different than lingering instance.

My original point was to make process executor exposed to Symfony\Process or our internal class :)
you can call it data lingering. I call it data ensuring by using objects.

> let's keep it single responsibility.

passing PID or Process object is not related for single responsibility. if you want single responsibility, move the kill function outside from ProcessExecutor or change his name

2023-01-24 16:43 UTC, o-kima commented on src/Remotisan.php
> +        Audit::updateProcessStatusByUuid($uuid, ProcessStatuses::KILLED);
so why not create a non static method on `Audit`?
```
public function setStatus($status): self
{
$this->process_status = $status;
$this->save();
return $this;
}

// Or even better:
public function markAsKilled($status): self
{
$this->process_status = ProcessStatuses::KILLED;
$this->save();
return $this;
}
```

and here call
```
$auditRecord->markAsKilled();
```

2023-01-24 16:49 UTC, o-kima commented on src/Remotisan.php
> +            throw new UnauthenticatedException("Action Not Allowed.", 404);
again, we should throw appropriate message.
`!$auditRecord` -> 404
`$auditRecord->user_identifier != $this->getUserIdentifier()` -> 401
`$auditRecord->process_status !== ProcessStatuses::RUNNING` -> 400/422

2023-03-13 12:57 UTC, kima92 reviewed
where is the worker command for checking new records in killing_key?

2023-03-13 12:57 UTC, kima92 commented on config/remotisan.php
> +    "server_guid_key"           => "remotisan:server_guid",
move to const instead of config?

2023-03-13 12:57 UTC, kima92 commented on src/Http/Controllers/RemotisanController.php
> +        try {
kill directly if same server?

2023-03-13 12:57 UTC, kima92 commented on src/ProcessExecutor.php
> +        $process = Process::fromShellCommandline("kill -9 {$auditRecord->getPid()}", base_path());
check isOwnedProcess here

2023-03-13 12:57 UTC, kima92 commented on src/ProcessExecutor.php
> +        return $pid;
return bool instead

2023-03-13 12:57 UTC, kima92 commented on src/ProcessExecutor.php
> +            " > {$output}; echo '{$uuid}' >> {$output}; php artisan remotisan:complete {$uuid}";
Remove `echo '{$uuid}'`. should be handled in remotisan:complete

2023-03-13 12:57 UTC, kima92 commented on src/Remotisan.php
> +        $this->instance_uuid = Storage::disk("local")->get("remotisan_server_guid");
Move to serviceProvider.
Use `cache()->driver("file")->rememberForever("remotisan:server_guid", fn() => Str::uuid()->toString())`

2023-03-13 12:57 UTC, kima92 commented on src/Remotisan.php
> +        $values = Cache::get($cacheKey);
can we use hash functions instead of manual add/remove from an array?

2023-03-13 12:57 UTC, kima92 commented on src/Remotisan.php
> +        if ($values !== (array)$values) {
!$values

2023-03-13 12:57 UTC, kima92 commented on src/Remotisan.php
> +        if ($this->instance_uuid !== $auditRecord->getInstanceUuid()) {
exception if the config is set off.

i suggest to check it in the beginning:

```
if (!config("remotisan.allow_process_kill", false)) {
     return false;
}
```

2023-03-13 12:57 UTC, kima92 commented on src/Remotisan.php
> +        if ($key = array_search($uuid, $values)) {
return 0, falsy value, if key is the first in the array, and won't delete it

2023-03-13 12:57 UTC, kima92 commented on src/Remotisan.php
> +            Artisan::call("remotisan:complete {$executionUuid}");
remove? we should return isEnded from the audit status, and not to call the complete if ended

2023-03-13 12:57 UTC, kima92 commented on src/ServerRegistration.php
> +class ServerRegistration
no need if using `cache()->driver("file")->rememberForever("remotisan:server_guid", fn() => Str::uuid()->toString())`

2023-03-13 12:57 UTC, kima92 commented on src/Remotisan.php
> +        $this->processExecutor->appendInputToFile($this->getFilePath($uuid), "PROCESS KILLED AT " . $dateTime);
not sure we need it

2023-03-13 12:57 UTC, kima92 commented on src/Models/Audit.php
> +    public function getPid(): int
remove attribute getters

2023-03-15 10:43 UTC, o-kima commented on src/ProcessExecutor.php
> +            throw new ProcessFailedException($process);
ProcessFailedException receives string, not process

2023-03-15 10:43 UTC, o-kima commented on src/Models/ProcessStatuses.php
> +namespace PayMe\Remotisan\Models;
Move outsode Models

2023-03-15 10:43 UTC, o-kima commented on src/Console/Commands/CompletionCommand.php
> +        $auditRecord = Audit::getByUuid($this->argument("uuid"));
validate exists

2023-03-15 10:43 UTC, o-kima commented on src/Console/Commands/CompletionCommand.php
> +    public function __construct()
remove?

2023-03-15 10:43 UTC, o-kima commented on src/Remotisan.php
> +            $auditRecord = Audit::getByUuid($uuid);
validate exists

2023-03-15 10:43 UTC, o-kima commented on src/Remotisan.php
> +            throw new UnauthenticatedException("Action Not Allowed.", 404);
`throw new RecordsNotFoundException` or better message

2023-03-15 10:43 UTC, o-kima commented on src/Remotisan.php
> +        if ($auditRecord == $this->getInstanceUuid()) { // if same instance, kill right away.
```
if ($auditRecord->instance_uuid == $this->getInstanceUuid())
```

2023-03-15 10:43 UTC, o-kima commented on src/Http/Controllers/RemotisanController.php
> +        return ["pid" => $pid];
its uuid now

2023-03-15 10:43 UTC, o-kima commented on src/ProcessExecutor.php
> +        usleep(4000);
I don't think you need `usleep` and `$process->stop()` as `run()` is sync

2023-03-15 10:43 UTC, o-kima commented on src/Remotisan.php
> +            $this->instance_uuid = Storage::disk("local")->get("remotisan_server_guid");
```
cache()->driver("file")->rememberForever("remotisan:server_guid", fn() => Str::uuid()->toString())
```
now can remove `ServerRegistrationCommand`

2023-03-15 11:14 UTC, o-kima commented on src/Remotisan.php
> +            "content" => explode(PHP_EOL, rtrim(File::get($this->getFilePath($executionUuid)))),
validate exists

2023-03-15 11:18 UTC, o-kima commented on src/Console/Commands/ProcessKillerCommand.php
> +    public function __construct(Remotisan $remotisan)
move Remotisan to Handle method (also has DI)

2023-03-15 11:21 UTC, o-kima commented on src/Console/Commands/ProcessKillerCommand.php
> +                if($killedUuid === $uuid) {
remotisan->killProcess already handled cleaming the cache list

2023-03-15 14:30 UTC, o-kima commented on composer.json
> +    "scripts": {
rollback

2023-03-15 14:32 UTC, o-kima commented on src/Console/Commands/ProcessKillerCommand.php
> +        foreach ($jobsUuidList as $k => $uuid) {
remove $k

2023-03-15 14:33 UTC, o-kima commented on src/Console/Commands/ProcessKillerCommand.php
> +        $jobsUuidList = Cache::get($cacheKey) ?? [];
maybe move to remotisan? $remotisan->getInstanceKillingSignals()

2023-03-15 14:38 UTC, o-kima commented on src/Remotisan.php
> +        if(config("remotisan.allow_process_kill", false) === true) {
So if feature is off we will send 404? :\

2023-03-15 16:06 UTC, o-kima commented on README.md
> +In additional, you would like to create supervisor worker to run `php artisan remotisan:process-killer` in each instance.
remove

2023-03-15 16:07 UTC, o-kima commented on src/Remotisan.php
> +            "isEnded" => ($auditRecord ? $auditRecord->getProcessStatus() : 2) === ProcessStatuses::COMPLETED
`!auditRecord || ($auditRecord->getProcessStatus() == ProcessStatuses::COMPLETED)`

Or make 2 -> enum

2023-03-15 16:09 UTC, o-kima commented on src/Remotisan.php
> +            if($key !== false) {
$key is always true if we got here. remove

2023-03-16 08:23 UTC, o-kima commented on remotisan_supervisor.conf
> +numprocs=3
numprocs=1
not sure we want to push this file. a note in the ReadMe is enough

2023-03-16 08:28 UTC, o-kima commented on src/Http/Controllers/RemotisanController.php
> +            $uuid = null;
if null should return `return response()->json([], 500)` as the ajax call just check status 200

2023-03-16 08:30 UTC, o-kima commented on src/Remotisan.php
> +        if ($auditRecord->getInstanceUuid() == $this->getInstanceUuid()) { // if same instance, kill right away.
move this check to top, as killProcess does all above checks already

2023-03-16 08:42 UTC, o-kima commented on src/Remotisan.php
> +            "isEnded" => ($auditRecord ? $auditRecord->getProcessStatus() : ProcessStatuses::COMPLETED) === ProcessStatuses::COMPLETED
maybe not running? we don't want the reader to read again if it killed

2023-03-16 16:04 UTC, o-kima commented on src/Models/Audit.php
> +        return $q->exists() ? $q->first() : null;
rollback to `return static::query()->where("uuid", $uuid)->first()`

->exists() will make a redundant SQL statement. if `->first()` didn't found a records it would return null anyway

2023-03-19 13:05 UTC, ranbahar commented on src/Remotisan.php
> +        if(config("remotisan.allow_process_kill", false) === true) {
New line before if

2023-03-20 11:54 UTC, ranbahar submitted a review, later dismissed

2023-03-20 12:36 UTC, o-kima approved these changes

2023-03-20 12:36 UTC, merged